import React from 'react';
import { StyleSheet } from 'react-native';

module.exports = StyleSheet.create({
    science:{
        backgroundColor: "#48D2961F",
        borderColor: "#48D296",
        borderWidth:1,
        color:"#48D296"
    },
    sports:{
        backgroundColor:"#FF84841F",
        borderColor:"#FF8484",
        borderWidth:1,
        color:"#FF8484"
    },
    politics:{
        backgroundColor:"#C47DEC1F",
        borderColor:"#C47DEC",
        borderWidth:1,
        color:"#C47DEC"
    },
    entertainment:{
        backgroundColor:"#5fa0d81F",
        borderColor:"#5fa0d8",
        borderWidth:1,
        color:"#5fa0d8"
    },
    money:{
        backgroundColor:"#e570cf1F",
        borderColor:"#e570cf",
        borderWidth:1,
        color:"#e570cf"
    },
    movies:{
        backgroundColor:"#62db621F",
        borderColor:"#62db62",
        borderWidth:1,
        color:"#62db62"
    },
    music:{
        backgroundColor:"#46d3d61F",
        borderColor:"#46d3d6",
        borderWidth:1,
        color:"#46d3d6"
    },
    technology:{
        backgroundColor:"#efae581F",
        borderColor:"#efae58",
        borderWidth:1,
        color:"#efae58"
    },
    world:{
        backgroundColor:"#ef87571F",
        borderColor:"#ef8757",
        borderWidth:1,
        color:"#ef8757"
    },

    scienceButton:{
        backgroundColor: "#48D2961F",
    },
    sportsButton:{
        backgroundColor:"#FF84841F",
    },
    politicsButton:{
        backgroundColor:"#C47DEC1F",
    },
    entertainmentButton:{
        backgroundColor:"#5fa0d81F",
    },
    moneyButton:{
        backgroundColor:"#e570cf1F",
    },
    moviesButton:{
        backgroundColor:"#62db621F",
    },
    musicButton:{
        backgroundColor:"#46d3d61F",
    },
    technologyButton:{
        backgroundColor:"#efae581F",
    },
    worldButton:{
        backgroundColor:"#ef87571F",
    },

    scienceText:{
        color: "#48D296AA",
    },
    sportsText:{
        color:"#FF8484AA",
    },
    politicsText:{
        color:"#C47DECAA",
    },
    entertainmentText:{
        color:"#5fa0d8AA",
    },
    moneyText:{
        color:"#e570cfAA",
    },
    moviesText:{
        color:"#62db62AA",
    },
    musicText:{
        color:"#46d3d6AA",
    },
    technologyText:{
        color:"#efae58AA",
    },
    worldText:{
        color:"#ef8757AA",
    }
});
